"""initial migration

Revision ID: 8d35b7d2013d
Revises: 
Create Date: 2020-01-08 20:05:37.343466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d35b7d2013d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_platform',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_platform_platform'), 'integration_platform', ['platform'], unique=True)
    op.create_table('url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_address'), 'url', ['address'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_address'), table_name='url')
    op.drop_table('url')
    op.drop_index(op.f('ix_integration_platform_platform'), table_name='integration_platform')
    op.drop_table('integration_platform')
    # ### end Alembic commands ###
